input: String
Version: String
DataDir: ExistingPath
NodeList:
    NodeListName:
        ParentNode: Config In NodeList
        Serial: Integer
        IP: IP
        Protocol: Protocol
Tags: List of String